# wrangler.toml
name = "apg-worker"
main = "src/index.ts"
compatibility_date = "2024-04-05" # Use a recent date

# Add bindings for secrets and environment variables
# Use 'wrangler secret put <VAR_NAME>' to set secret values
[vars]
LLM_MODEL_NAME = "claude-3-7-sonnet-20250219"
LLM_SYSTEM_PROMPT = ""
LLM_MAX_TOKENS = "3500"
LLM_PROMPT_TEMPLATE = "Write a Paul Graham essay about {short_description}"
RESTRICT_TO_CURRENT_MODEL = true
RESTRICT_TO_CURRENT_PROMPT = false

# Secrets (set via `wrangler secret put`)
# ANTHROPIC_API_KEY
# SUPABASE_URL
# SUPABASE_SERVICE_KEY

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true
